---
# tasks file for wordpress_ubuntu
- name: install wordpress
  remote_user: ubuntu
  hosts: all
  become: true
  become_user: root
  gather_facts: true
  tasks:
  - name: Install required software
    # when: CONDITION HER
    apt: 
      name: "{{ item }}"
      state: present
      update_cache: yes
    with_items:
    - apache2
    - php7.4 
      
    

  - name : Get wordpress
    get_url:
      url: https://wordpress.org/wordpress-4.0.32.tar.gz
      dest: /tmp/wordpress-4.0.32.tar.gz
      mode: '0440'

      # 
