---
- name: Add IAM group
  hosts: localhost
  tasks:
  - name: Create Two Groups, Mario and Luigi
    community.aws.iam:
      iam_type: group
      name: "{{ item }}"
      state: present
    loop:
     - DevOps
    register: new_groups